### ISSUE TITLE
Need a way to inspect the body of request before flight

### ISSUE THREAD

**Issue by joegaudet** [dispatch/reboot#104]
I'm debugging an issue where I don't have access to the logs of the server under test, and I suspect the body payload is not being properly encoded. Is there a method for inspecting the request, url / headers / queryparams / body before the request is executed? 

Here is some example code that is failing. Perhaps there's something I'm missing, the operator syntax is a bit arcane. I assumed there was encoding going on using the regular addParameter function, or the sugared version of it. I couldn't be sure so I tried this approach, but still having no success.

Any thoughts would be helpful.

``` Scala
  val formsEndpoint = host("forms.hubspot.com").secure / "uploads" / "forms" / "v2"


  override def logger = Logger("HubSpotIntegration")

  /**
   * Internal Event generate when new learndot is created view self signup
   *
   * @param user owner of the new Learndot
   * @param organization organization associated with the new Learndot
   */
  override def onSelfSignup(user: User, organization: Organization, hubSpotContextOption: Option[HubSpotContext]) {

    val hubSpotContext = hubSpotContextOption.getOrElse(HubSpotContext("", ""))

    val payload = Map(
      "firstname" -> user.firstName,
      "lastname" -> user.lastName.getOrElse(""),
      "email" -> user.email,
      "domain" -> organization.hostUrl,
      "leadsource" -> "Learndot Signup",
      "hs_context" -> JsonUtil.generate(hubSpotContext).toString
    ).map({ case (key, value) => s"$key=${encode(value)}" }).mkString("&")

    val portalId = "296336"
    val formGuid = "6c1fcfa5-e069-4321-9bcc-4adc17d68663"

    val endpoint = formsEndpoint / portalId / formGuid

    info(s"Shipping payload to HubSpot ${endpoint.url}")

    info(hubSpotContext.toString)

    val request = endpoint.POST
    request.setContentType("application/x-www-form-urlencoded", StandardCharsets.UTF_8.name)
    request.setBody(payload)

    val resultFuture = Http(request OK as.String)
    val result = resultFuture()
    println(resultFuture.print)
  }


  private def encode(string: String) = {
    URLEncoder.encode(string, StandardCharsets.UTF_8.name)
  }
```

**Comment by farmdawgnation** [comment]
Hi there,

I'm sorry you didn't get a better answer to your question when you posted it. I've been working on improving the support dispatch users get since I took over as maintainer.

I'm not sure if this is still a pertinent issue for you given the age of the post, but if it is please comment back. I'm sure there's a way to do this by calling on some of the underlying HTTP library code, but without knowing what version of Dispatch you were using I wouldn't know where to start.

Cheers,
Matt
