### ISSUE TITLE
url secure is buggy because of old async-http-client version

### ISSUE THREAD

**Issue by eklavya** [dispatch/reboot#108]
Hi,

I am facing this problem where query parameters are repeated after making a URL secure. I realized this is because in old (1.8.x) versions of async.http.client.

In Dispatch:
https://github.com/dispatch/reboot/blob/0.11.3/core/src/main/scala/requests.scala#L96:L98
```scala
def secure = {
    subject.setUrl(RawUri(url).copy(scheme=Some("https")).toString)
  }
```

In async-http-client 1.8.x:
https://github.com/AsyncHttpClient/async-http-client/blob/1.8.x/src/main/java/com/ning/http/client/RequestBuilderBase.java#L383:L393
```scala
public T setURI(URI uri) {
        if (uri.getHost() == null)
            throw new NullPointerException("uri.host");
        if (uri.getPath() == null)
            throw new NullPointerException("uri.path");
        request.originalUri = uri;
        addQueryParameters(request.originalUri);
        request.uri = null;
        request.rawUri = null;
        return derived.cast(this);
    }
```

query parameters are wrongly appended again to the complete uri.

How to reproduce:
```scala
import dispatch._, Defaults._
    val urlSuffix = "&q=1"
    val u = "http://localhost:9000/path?"
    println(u)
    println(urlSuffix)
    val ur = url(u + urlSuffix)
    println(ur.url)
    println(ur.secure.url)
    println(ur.secure.secure.secure.url)
```

I confirmed that upgrading to newer async-http-client works by using async-http-client-1.9 branch of @agourlay

**Comment by n8han** [comment]
Okay, should be fixed in 0.11.3 then.

**Comment by eklavya** [comment]
Thanks @n8han , waiting for 0.11.3 for production deployment.

**Comment by n8han** [comment]
Okay, it's released now if you want to give it a whirl. I'll announce
tomorrow morning after I put some release notes together.

**Comment by n8han** [comment]
Oh dear, the new version of async client brings back the perennial problem of the scala console failing to close after using dispatch. I don't suppose any of our async client 1.9 fans would like to find and fix the "bug" it introduces? You have figure out which thread, usually a thread pool, is being started without being marked a daemon thread, which is something we do only when we think we're running in a cosole. (I don't really consider it a bug, more going the extra mile, but users expect it.)

**Comment by eklavya** [comment]
Thanks @n8han :+1: 

Regarding the bug, I don't think I am a fan of async client 1.9 it's just that 1.8.x is broken for me ;)
If I were to take a look at this bug how would I check if we were running in scala repl and make all threads daemon? Or are you saying that all threads should be daemon threads in dispatch and the bug is about finding out which ones are not?
