### ISSUE TITLE
Http.configure creates a new HTTP client but doesn't shutdown the old reference. 

### ISSUE THREAD

**Issue by damienlevin** [dispatch/reboot#114]
The following code creates a new HTTP client but doesn't shutdown the old reference. 
https://github.com/dispatch/reboot/blob/0.11.3/core/src/main/scala/execution.scala?L=19#L20

**Comment by cb372** [comment]
+1

**Comment by farmdawgnation** [comment]
This has been resolved in Dispatch 0.12.x and Dispatch 0.13.x. Releases including this fix are forthcoming.
