### ISSUE TITLE
Dispatch 0.11.3 breaks binary compatibility from 0.11.1

### ISSUE THREAD

**Issue by eed3si9n** [dispatch/reboot#116]
## steps
1. Publish a library that uses Dispatch 0.11.1's `req.toRequest.getRawUrl`.
2. Try using the library with Dispatch 0.11.3.
## problem

Runtime error.
## expectation

Binary incompatible update bumps up 0.12.x.
## notes
#102 changed underlying async-http-client version to 1.9.11. According to their [migration guide](https://github.com/AsyncHttpClient/async-http-client/blob/master/MIGRATION.md):

> AsyncHttpClient v1.9 is a preview of v2, so it comes with some breaking changes.

Apparently `getRawUrl` is one of the methods that was axed in 1.9.x.

**Comment by eed3si9n** [comment]
Just came across another change that requires source change: `setConnectionTimeoutInMs` -> `setConnectTimeout` - https://github.com/eed3si9n/scalaxb/pull/352#issuecomment-137246840

Ref eed3si9n/scalaxb#352

**Comment by mdedetrich** [comment]
@eed3si9n Is it possible to close this?

0.12.0 was just released which should have pushed most of these bincompat issues to a new stable release, not sure if you still want to track this

**Comment by eed3si9n** [comment]
I'd be happy to close this, but I think Dispatch should adopt bincompat guarantees during 0.12.x series, 0.13.x, and so on.
