### ISSUE TITLE
App hangs if Http.configure has been used

### ISSUE THREAD

**Issue by vchekan** [dispatch/reboot#121]
I have a simple console app, which grabs text from http, process it and outputs test result.
If I use 

``` scala
val req = Http.configure(_ setFollowRedirects true)(url(link) OK as.Response(_.getResponseBodyAsStream))
```

then my app will hang after main() is complete.
But if I remove configure call, then the app exits successfully.

Version: 'net.databinder.dispatch:dispatch-core_2.11:0.11.2'

**Comment by farmdawgnation** [comment]
@vchekan You may need to invoke `Http.shutdown()` before the end of your main method, or potentially [add a shutdown hook](https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#addShutdownHook(java.lang.Thread)) to your application.

I'll leave this open in case you want to respond, but given this is > 1 year old I'll go ahead and close it if I don't hear from you in a day or so. :)
