### ISSUE TITLE
setUseProxyProperties does nothing

### ISSUE THREAD

**Issue by henry0312** [dispatch/reboot#122]
The below code does nothing because [proxyServerSelector](https://github.com/AsyncHttpClient/async-http-client/blob/1.9.x/src/main/java/com/ning/http/client/AsyncHttpClientConfig.java#L996-L1000) already has an instance of ProxyServerSelector (i.e. proxyerverSlector isn't null).

``` scala
val http = Http.configure { builder =>
  builder.setUseProxyProperties(true)
}
```

**Comment by farmdawgnation** [comment]
@henry0312 I believe this is fixed now, yes?
