### ISSUE TITLE
Upgrade to latest async-http-client version

### ISSUE THREAD

**Issue by goyalr41** [dispatch/reboot#125]
The latest async-http-client library version is 1.9.31 but dispatch is using version 1.9.11. This leads to failure while using other libraries because there are changes in both the versions of ning's http-client. Any plans to update the version?

**Comment by chuck-g** [comment]
The latest is now 1.9.39. This really should be upgraded.

**Comment by Rydgel** [comment]
+1 on this

**Comment by cli0** [comment]
Has there been any upgrade or does dispatch still use 1.9.11?

**Comment by farmdawgnation** [comment]
Hi everyone, I'm going to be looking at an upgrade on this front soonish. I just came on as maintainer, so dependency bumps will be the first thing on the list. :)

**Comment by farmdawgnation** [comment]
Hello, hello.

I'm going to take a look at releasing a 0.12.2 that upgrades the 1.9.x series version.

Dispatch v0.13.0-M1 has just been released that uses AHC 2.0.32.

We'll be releasing a v0.14.0-SNAPSHOT soon that's based on AHC 2.1.x alphas. I'll close this issue in favor of a more specific one for 0.12.2. Thanks!
