### ISSUE TITLE
Scala 2.12.0

### ISSUE THREAD

**Issue by QuadStingray** [dispatch/reboot#134]
Please build Dispatch with Scala 2.12.0

**Comment by SethTisue** [comment]
no commits for well over a year, so I think a new maintainer will need to be found. anyone out there want to take it on? even if the project doesn't really move forward in any substantive way, it would be good at least have someone who's willing to do basic keeps-the-lights-on stuff like a 2.12 release

**Comment by mdedetrich** [comment]
I would take it on, but maybe we should wait for the maintainer to respond in a couple of days. Is he contactable by email?

**Comment by mdedetrich** [comment]
Can't update until https://github.com/unfiltered/unfiltered/issues/319 is solved

**Comment by SethTisue** [comment]
@eed3si9n are you able to help with this (adding new maintainers) at the same time as https://github.com/unfiltered/unfiltered/issues/320?

**Comment by eed3si9n** [comment]
I'm just an outside cheerleader, and don't have membership to either orgs.

**Comment by SethTisue** [comment]
@softprops do you have the same magic powers here as you did over in unfiltered-land?

**Comment by mdedetrich** [comment]
Pull request for unfiltered for 2.12 support has been made here https://github.com/unfiltered/unfiltered/pull/330

When its published to a version than Dispatch can follow

**Comment by ashawley** [comment]
Is the proposal to build dispatch 0.11.2 for Scala 2.12?  Because that would be great.

Isn't the important issue having the magical-powers to publish to Sonatype, and not so much about GitHub?

**Comment by mdedetrich** [comment]
> Is the proposal to build dispatch 0.11.2 for Scala 2.12? Because that would be great.

It can't currently be built due to unfiltered dependency not working for Scala 2.12

> Isn't the important issue having the magical-powers to publish to Sonatype, and not so much about GitHub?

Yup, @SethTisue messaged the maintainer already

**Comment by ashawley** [comment]
> It can't currently be built due to unfiltered dependency not working for Scala 2.12

dispatch 0.11.2 depends on unfiltered 0.8.4.  Looks like the unfiltered issue you raised is fixing 0.9.0.  Shouldn't it be for 0.8.4?

**Comment by mdedetrich** [comment]
I suppose its assumed that Dispatch will update its dependency, in the worst case I don't think that backporting would be that painful

**Comment by ashawley** [comment]
Seems risky.  Looks like unfiltered/unfiltered#321 removes dispatch as a (circular) dependency, replacing it with www.github.com/square/okhttp.  Will that change introduce source compatibility problems?  I haven't pulled on the thread long enough to know what's at the end.

**Comment by softprops** [comment]
> @softprops do you have the same magical magical-powers-granting powers here as you did over in unfiltered-land?

I just have the default member level permissions here so I can't invite new members :/ I think only @n8han can invite new members. There's only two members in listed under https://github.com/orgs/dispatch/people.

**Comment by ashawley** [comment]
Looking further, it appears that unfiltered isn't a true circular dependency.  It's only a dependency for testing.  Scala 2.12 will compile 0.11.2 without a problem once you drop it.  Perhaps, there just needs to be a 0.11.2-RC1 for Scala 2.12 published?

**Comment by ashawley** [comment]
I've suggested that a build of unfiltered-netty-server 0.8.4 be published for Scala 2.12 in unfiltered/unfiltered#338

But again, a build of Dispatch for 2.12 can be done without Unfiltered.

Does anyone have the permissions to publish a 0.11.2 build for Scala 2.12 to Sonatype?

**Comment by ashawley** [comment]
A 2.12 build of Dispatch 0.11.2 would require moving json4s from 3.2.10 to 3.4.2 and scala-xml from 1.0.1 to 1.0.5

See f511a25 for producing a 0.11.2-RC1 build from the 0.11.2 tag.

Publishing would be:

```
$ sbt ++2.12.0 publish
```

The changes for json4s are:

https://github.com/json4s/json4s/compare/v3.2.10...v3.4.2

The changes for scala-xml are:

https://github.com/scala/scala-xml/compare/v1.0.1...v1.0.5

**Comment by mdedetrich** [comment]
@ashawley This is just for building though, tests are still broken right (due to unfiltered not being published)

**Comment by leonardehrenfried** [comment]
I also want to chime in and say that I'm willing to help out with the maintainership. However getting approval and/or credentials from @n8han seems to be the top priority. Has anyone succeeded in getting in touch with him?

I don't wanna be all stalkerish but his twitter account (https://twitter.com/n8han) has been active in the last 24h so he propably hasn't gone off the grid.

**Comment by mdedetrich** [comment]
@leonardehrenfried I have received ownership of the organisation, I think the only thing missing is publish rights to sonatype

**Comment by leonardehrenfried** [comment]
Good to hear.

Do you plan to cut the Scala 2.12 release from this repo (reboot) or the main one (dispatch/dispatch)?

**Comment by mdedetrich** [comment]
From reboot (reboot is meant to be the latest version/implementation of dispatch)

**Comment by fbascheper** [comment]
A build of unfiltered 0.8.4 for Scala 2.12 isn't going to happen, but instead a build of unfiltered v0.9.0-beta2 has been published to maven central. See [here](https://repo1.maven.org/maven2/ws/unfiltered/unfiltered_2.12/0.9.0-beta2/unfiltered_2.12-0.9.0-beta2.pom) for the pom file. 

Any chance this helps in getting a first 2.12 build of dispatch?

**Comment by mdedetrich** [comment]
@fbascheper Thanks, I will have a look into it

**Comment by fbascheper** [comment]
Can you take a look at this request. It fixes the build on my machine. 
I still have a couple of warnings though, and I'd like to upgrade scalacheck to a recent version, which also introduces a few extra warnings (sigh).

**Comment by mdedetrich** [comment]
Thanks, I have merged the pull request. I am just waiting for Sonatype permissions to deploy know. I have also bumped the version to 0.12.0.

**Comment by farmdawgnation** [comment]
@mdedetrich Do you have an ETA on getting those Sonatype permissions? I've got another project I'd like to add 2.12 support for, but I'm waiting on Dispatch to be updated.

Also, would y'all like help maintaining dispatch? I sent an email to @n8han awhile back offering to help since I've got so many projects that use it and it's still my favorite HTTP abstraction for Scala, but never got a reply.

**Comment by mdedetrich** [comment]
@farmdawgnation @n8han Is currently on holidays but when he returns he needs to make an issue on SonaType to add me as part of the contributors, so I wouldn't expect anything really soon

Regarding maintenance, I don't have a personal issue with it but maybe its better to see what @n8han thinks

**Comment by raboof** [comment]
Can we post a SNAPSHOT release somewhere while we wait for the proper sonatype credentials to come through?

**Comment by raboof** [comment]
I uploaded `"net.bzzt" %% "dispatch-core" % "0.12.0-SNAPSHOT"` to Sonatype Snapshots - this is 88fde3acbdc4763794cab816f00ed8d855ade634 with the `organization` and `version` settings modified.

**Comment by mdedetrich** [comment]
I am going to reopen this issue until I get to deploy

Unfortunately, I am not getting a response from @n8han in regards to giving me deploy rights on sonatype (he is currently on vacation so it may take a while)

**Comment by mdedetrich** [comment]
Since there are also some pull requests with issues that have been umerged and we are doing a major bump, I am going to merge this pull requests and retag for v0.12.0

**Comment by leonardehrenfried** [comment]
I know this is ungrateful but if the original maintainer isn't responding it may be worth publishing this under a new group id.

This issue has been open for a while.

**Comment by ashawley** [comment]
That was how unfiltered/unfiltered#351 had to be resolved.

**Comment by leonardehrenfried** [comment]
Maybe we should give ourselves one more week and then deploy under a different group id.

What do people think about that?

**Comment by mdedetrich** [comment]
@leonardehrenfried Sure thing, I am happy with that. We should probably try and find a new group id that works with the project

**Comment by mdedetrich** [comment]
https://issues.sonatype.org/browse/OSSRH-27773

Should get the permissions within a couple of days at which point I will deploy

**Comment by leonardehrenfried** [comment]
Oh, that's fantastic news!

I was hoping we would be able to keep the group id and resolve this in
cooperation with Nathan.

**Comment by mdedetrich** [comment]
Okay so the permission came through, I will wait two days to see if we can get https://github.com/dispatch/reboot/pull/128 in for 0.12.0 (@alexdupre just has to rebase the branch against 0.12.0)

**Comment by ashawley** [comment]
Should 0.12 target 1.9, and AHC 2.0 could be 0.13?  I'm amending my previous suggestion in #128.  I noticed Gigahorse did something similar with AHC versions and its own releases.

**Comment by mdedetrich** [comment]
I think if possible (and easy), getting AHC 2.0 into 0.13 would be nice, but only if it doesn't require a lot of effort/break a lot of stuff, @ashawley correct me if I am wrong

**Comment by alexdupre** [comment]
I did the upgrade to AHC 2.0 in Gigahorse and added support for WebSocket, given that there was no intention to maintain and further support dispatch. At the moment I'm using my local dispatch 0.11.4 release only with scalaxb that hasn't been migrated to Gigahorse yet, but I expect that the rebase of my work on 0.12 branch will be straightforward.

**Comment by mdedetrich** [comment]
Okay in that case, I think 0.13 is a better target (didn't realise the change was that big). Will release dispatch with the current 0.12.0 branch (@ashawley we can probably fix up the branches afterwards)

**Comment by alexdupre** [comment]
Dispatch 0.11.3 already targets AHC 1.9, why would you like to have the first 0.12 release to target the same old version?

**Comment by mdedetrich** [comment]
It was a mistake on my part, got mixed up between the versions

**Comment by mdedetrich** [comment]
Okay, 0.12.0 has been released. It should be available on Maven in around an hour

**Comment by jvican** [comment]
It's great to see people maintaining dormant libraries the community depends on. I find this is the natural way of growing projects and communities around them. Thanks.
