### ISSUE TITLE
dispatch test suite intermittently hangs in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [dispatch/reboot#137]
seen at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/1177/console and again at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1180/consoleFull

I will disable running dispatch's test suite as part of the community build until this can be investigated and fixed.

**Comment by SethTisue** [comment]
It isn't even very "intermittent". It's been freezing about 50% of the time

**Comment by mdedetrich** [comment]
I will try and have a look into this next week

**Comment by ashawley** [comment]
Perhaps #118 would still fix it?

**Comment by fbascheper** [comment]
I've submitted a pull request #139 that upgrades the async http client, cherry-picking a couple of related PR's. I haven't seen any issues with Travis in my build since.

**Comment by farmdawgnation** [comment]
@SethTisue Is this still an issue

**Comment by SethTisue** [comment]
> Is this still an issue?

The test suite remains disabled in the community build. If you have reason to believe this might be fixed, I could re-enable the tests and see if we get intermittent failures. But if nothing has been done to address this, then presumably it's still broken.

**Comment by farmdawgnation** [comment]
@SethTisue Got it. I'm going to investigate the resource leak caused by configure and then we can revisit this.

**Comment by farmdawgnation** [comment]
@SethTisue I believe we fixed the resource leak here. Can you give it a shot in the community build for us?

**Comment by SethTisue** [comment]
scala/community-builds@6d3c0782c21e80ef5aac6e989fd2aefc9fad494a — let's see how it goes. we can reopen this if there's trouble. thanks!
