### ISSUE TITLE
documentation should be updated: 0.11.2 -> 0.12.0

### ISSUE THREAD

**Issue by vn971** [dispatch/reboot#146]
The central page of the site says the current version is 0.11.2
http://dispatch.databinder.net/Dispatch.html

This is probably a bit outdated. Am I right that 0.12.0 is recommended to work with, too?

**Comment by farmdawgnation** [comment]
That is correct, unfortunately I think @n8han is the only one with access to that. @mdedetrich may be able to correct me if I'm wrong.

**Comment by mdedetrich** [comment]
Yeah I have no idea how to modify that, you would have to contact @n8han

**Comment by xuwei-k** [comment]
FYI, unfiltered migrate to github pages with paradox

- https://github.com/unfiltered/unfiltered/pull/361
- https://github.com/unfiltered/unfiltered/issues/353
- https://github.com/unfiltered/website

**Comment by farmdawgnation** [comment]
In the interest of not boiling the ocean I've settled for migrating the documentation site to GitHub pages using pamflet. I'll talk to @n8han out of band about getting a 301 from the old doc site to the new one. The README has been updated to point to the new location.

Closing this issue.

**Comment by vn971** [comment]
@farmdawgnation thanks
