### ISSUE TITLE
Find new maintainer

### ISSUE THREAD

**Issue by mdedetrich** [dispatch/reboot#148]
For reasons of personal time, I no longer have an interest in maintaining dispatch for the future. I helped out in the past mainly to get Dispatch to work with Scala 2.12.x series so that Scala 2.12.x didn't break a lot of existing community code. Futhermore I am not really familiar with the internals of Dispatch, so I am not the best person to take care of it.

Would it be possible for someone who has an interest in using Dispatch in the future to take the leads as a maintainer? @ashawley @farmdawgnation I believe you guys were interested?

**Comment by ashawley** [comment]
Nathan left some big shoes to fill.    Thanks for your work on this @mdedetrich.  It will take a lot of people to keep this project going.  Maybe @fbascheper would be interested in maintainership?

**Comment by farmdawgnation** [comment]
I'd be willing to lead the charge on maintaining this.

**Comment by farmdawgnation** [comment]
Of course, I, like most folks, have a lot going on, but I've gotten enough value out of this library to make some time for it. :)

**Comment by mdedetrich** [comment]
@farmdawgnation Can you email me your sonatype account? If you don't have one then you need to set one up. This will give you the ability to publish Dispatch

**Comment by farmdawgnation** [comment]
Yep!

**Comment by farmdawgnation** [comment]
Guess we can mark this as closed? :D
