### ISSUE TITLE
Rename this repo to "dispatch"

### ISSUE THREAD

**Issue by ashawley** [dispatch/reboot#151]
See dispatch/dispatch#105

Send an email to the dispatch mailing list about the change with instructions on pointing their git config to the new remotes.

**Comment by farmdawgnation** [comment]
I'm not sure about that, but renaming dispatch/dispatch to dispatch/classic does make sense...

**Comment by farmdawgnation** [comment]
After doing more thought on this, I think I'm going to keep this repo named dispatch/reboot for now. dispatch/dispatch has been renamed dispatch/classic and now direct folks who have issues with the latest Dispatch code to come here. Let's see how that does for now.
