### ISSUE TITLE
Add version table to README

### ISSUE THREAD

**Issue by ashawley** [dispatch/reboot#152]
The versions of Java, AHC and Dispatch need to be documented to make people aware of what version supports what, including historical releases.

**Comment by fbascheper** [comment]
👍  I just created #153 to add the latest version to the readme.

**Comment by farmdawgnation** [comment]
I've added some documentation of this for the supported releases: 0.12.x and 0.13.x. I don't plan on supporting earlier than 0.11.x, so I think we probably omit those for now.

WDYT?

**Comment by farmdawgnation** [comment]
This has been done in greater detail, btw. Closing this.

**Comment by ashawley** [comment]
Yes, the current table in the README is more of what I had in mind.  People might care less about branches or support expectations.  Replacing those with Java version(s) would be better.  Unfortunately, there are like four versions of Java out there in the wild these days — 6, 7, 8, 9.

**Comment by farmdawgnation** [comment]
Thanks for the feedback. I actually mention at the top of the README "Dispatch requires that you use Java 8 as AHC requires it."

But you're right. There are many Javas.
