### ISSUE TITLE
Release version for Scala 2.11/2.12 for dispatch with AHC 2.0

### ISSUE THREAD

**Issue by simonstuck** [dispatch/reboot#154]
Hi all,

Thanks for the successful port to AHC 2.0. When do you expect to perform a release and publish the new artefacts? I myself am very much interested in the Scala 2.11 variant. 

Thanks,
Simon

**Comment by farmdawgnation** [comment]
It'll probably be sometime this weekend when I have the time to audit the code one last time and spin the release.

**Comment by simonstuck** [comment]
Perfect, thank you 👍

**Comment by farmdawgnation** [comment]
This has been release to Sonatype as v0.13.0-M1. We'll evaluate how it does before calling it final.
