### ISSUE TITLE
Updating from 0.8 to 0.13

### ISSUE THREAD

**Issue by ricsirigu** [dispatch/reboot#160]
I'm trying to migrate the lift-omniauth library to scala 2.12 but in addition to dispatch-core it also has the following dependencies

```
      "net.databinder" %% "dispatch-http" % "0.8.10",
      "net.databinder" %% "dispatch-oauth" % "0.8.10",
      "net.databinder" %% "dispatch-http-json" % "0.8.10"
```

Where can I find those?

**Comment by maizy** [comment]
Those deps are from dispatch classic - https://github.com/dispatch/classic

**Comment by ricsirigu** [comment]
I know, but do I still need them? Do I have to compile them by myself to target scala 2.12?

**Comment by fbascheper** [comment]
Most likely you don't need them. Maybe we can help if you could give us some insights in the compilation errors you are encountering. Or even a WIP git fork with your initial work on this port. 
FWIW you can find the published artifacts [here](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22net.databinder.dispatch%22%20AND%20v%3A%220.13.0%22).

**Comment by farmdawgnation** [comment]
@ricsirigu I'd recommend upgrading to Dispatch 0.13.x if you want to build for 2.12. The "classic" version of Dispatch is, quite simply, ancient. The underlying HTTP client between 0.8.x and 0.13.x has changed to the AsyncHttpClient which stands to have a _number_ of performance improvements when sites get busy. The entire API is now async and returns `Future`s. Also, with the recent work to allow auto-conversions between `Future` <-> `LAFuture` in Lift, this should actually make the interface between lift-omniauth and the calling code smoother.

**Comment by farmdawgnation** [comment]
@ricsirigu It looks like this issue can be considered closed. Please feel free to comment back / reopen if there's more here to discuss.
