### ISSUE TITLE
setting request body with << changes method from PUT to POST

### ISSUE THREAD

**Issue by stephennancekivell** [dispatch/reboot#216]
Consider the following two definitions of a request. They should be equivalent, but the `<<` one becomes a POST request.

```
(localhost / "echobody").PUT.setBody(sample) > as.String
(localhost / "echobody").PUT << sample > as.String
```

I've put together a failing unit test here.
https://github.com/stephennancekivell/reboot/commit/05c10d8905f2f3e1697d608ea8302b28e9e90dc9

I think the issue has something to do with `implyMethod(..)` and `RequestBuilderVerbs.methodExplicitlySet`

This seems to be a regression between dispatch `0.12` and `1.1`

**Comment by jakehschwartz** [comment]
@stephennancekivell It was bugging me too, so I fixed it and there is a PR for it now. Thanks for the unit test!

**Comment by farmdawgnation** [comment]
Thanks for the bug report (and the PR). I really only get time for OSS on weekends so I'll try to make time for this on Saturday

**Comment by jakehschwartz** [comment]
Took a second step at it with https://github.com/dispatch/reboot/pull/218

**Comment by farmdawgnation** [comment]
#218 has been merged. I'm cutting new releases now.

**Comment by farmdawgnation** [comment]
Dispatch 1.0.2 and 1.1.1 have been released with the fix. They should show up on Sonatype in an hour or two. Thanks y'all!

**Comment by stephennancekivell** [comment]
thanks Matt
