### ISSUE TITLE
Requesting URLs with custom parameters is not possible

### ISSUE THREAD

**Issue by hbergmey** [dispatch/reboot#224]
I have to GET a JSON object from a service that requires selection of the kind of its result by providing a singular request parameter, that does not follow the key-value-scheme. For example:

`https://myservice.com/mypath?myparam`

While perfectly ok from perspective of the HTTP spec, there is no way to express request parameters like this in Dispatch. `Req.setQueryParameters` expects parameters only as a `Map[String, Seq[String]]` and would generate an equals sign `=` after a key, in case of a parameter value `Seq.empty`, or would return with an NPE if the value is set to `null`

`https://myservice.com/mypath?myparam=` (WRONG)

It neither possible to simply define the complete Request url like this:

`url("https://myservice.com/mypath?myparam")`

As parsing of URL parameters (everything behind the `?`) is domain specific and service routes and protocols can generally not be changed by client developers, Dispatch HTTP should be able to generate any kind of custom parameters.

I tried to implement a custom RequestBuilder by extending RequestBuilderBase, but I was unable to get it to work. The standard `org.asynchttpclient.util.UriEncoder` would support `null` values in `appendRawQueryParam` and would generate the URL without the equals sign, but working with `null` on an API is undesirable and currently the aforementioned NPE is thrown.

**Comment by farmdawgnation** [comment]
Thanks for reporting this issue.

I think a reasonable solution to this is to have `Seq.empty` stop the creation of the `=`. I'd argue this is the behavior one would expect, anyway, so we don't need a major version bump to indicate a breaking change. I'll see what I can do about fixing that up this weekend when I have some FOSS time.

**Comment by farmdawgnation** [comment]
Okay, @hbergmey, I've dug into this a bit. As a work-around you might consider using our `addQueryParameter` variant and providing a `null` to it. That should avoid the NullPointerException of the  `setQueryParameters` currently experiences when you pass `null`.

I think what we'll ned to do is add a variant of `addQueryParameter` that takes an `Option` and rework how `setQueryParameters` works internally.

**Comment by hbergmey** [comment]
An alternative would be an explicit model of different parameter types, like key value pairs and single expressions. But that would result in a bigger API change. I think an `Option` is reasonable.

**Comment by farmdawgnation** [comment]
Classifying this as an improvement, not a bug. I think the nature of the previous behavior, while unexpected, isn't something I'm comfortable in back-porting to a previous release even though I _am_ comfortable changing that behavior as a non-API-breaking change in a minor point release. This will ship with 1.2.0, accordingly.

**Comment by hbergmey** [comment]
Thank you very much for solving this, over the holidays even. I was OOO until today and have just tested the API request with a local 1.2.0-SNAPHOT build and a Seq.empty value. It works as expected now.

May I kindly ask, whether the 1.2.0 release is already somwhere on the horizon? I will have to use this in production soon and I am unsure how much risk there is in employing a locally build SNAPSHOT. Especially because I have to upgrade from 1.0.1. As far as I can tell from the git log and release notes, I do not expect all too much trouble, because the APIs I am accessing work with UTF-8, but I'd rather be sure to not miss anything.

**Comment by farmdawgnation** [comment]
I can go ahead and release it this week.
