### ISSUE TITLE
Emoji character in domains not recognized correctly (punycode)

### ISSUE THREAD

**Issue by redsk** [dispatch/reboot#230]
```
val u = "http://🔫🍸👙👩👙👚📿👒.ga"  // CAREFUL, NSFW
url(u).url
```
leads to 
```
java.net.URISyntaxException: Expected authority at index 7: http://
  java.net.URI$Parser.fail(URI.java:2848)
  java.net.URI$Parser.failExpecting(URI.java:2854)
  java.net.URI$Parser.parseHierarchical(URI.java:3102)
  java.net.URI$Parser.parse(URI.java:3053)
  java.net.URI.<init>(URI.java:588)
  dispatch.RawUri.toUri(uri.scala:23)
  dispatch.RawUri.toString(uri.scala:24)
  dispatch.url$.$anonfun$apply$3(requests.scala:102)
  dispatch.Req.requestBuilder$1(requests.scala:48)
  dispatch.Req.toRequestBuilder(requests.scala:53)
  dispatch.Req.toRequest(requests.scala:61)
  dispatch.UrlVerbs.url(requests.scala:125)
  dispatch.UrlVerbs.url$(requests.scala:125)
  dispatch.Req.url(requests.scala:17)
```

Its punycode [1] conversion [2] (`http://xn--vj8hunuaaf2g65c5j.ga/` - NSFW!) works as expected.

[1] https://en.wikipedia.org/wiki/Punycode
[2] used converter: https://www.punycoder.com/

**Comment by farmdawgnation** [comment]
Find me a different working URL to test against and I'm happy to consider investigating a fix here, but I'm not adding this URL to my test suite and I'm also not particularly interested in running requests to this URL from my development environment.

Closing as a "won't do" for now, but feel free to reopen the issue with a SFW URL when you have one.
