### ISSUE TITLE
dynamic url host issue

### ISSUE THREAD

**Issue by 0xb0bb** [dispatch/reboot#39]
when trying to build a dynamic url to take advantage of url encoding a call to host("domain.com") returns a RequestBuilder, however when provided as an arg to Http I get a promise(-incomplete-)  

If I prepend the domain with http:// ie. host("http://domain.com") I get a  Promise(!http://http://pubsub.pubnub.com/!) which is obviously not a valid url.  I am stuck here

**Comment by farmdawgnation** [comment]
@0xb0bb It sounds like this issue was resolved so I'm going to close this ticket. Let me know if I'm misunderstanding something! :)
