### ISSUE TITLE
when http.configure is called, InternalDefaults.client is no longer maintained, and causing "AsyncHttpClient.close() hasn't been invoked, which may produce file descriptor leaks"

### ISSUE THREAD

**Issue by sizheng** [dispatch/reboot#53]
Once dispatch.Http.configure is called, it's basically creating a new httpasynclient instead of reusing the InternalDefaults.client one, which causing two problems - 
1) shutdown has to be explicitly called
2) all goodness about nioClientSocketChannelFactory is gone

It would be great if there is an override to respecify the configuration ( well, I mainly care about the connectionTimeout and requestTimeout) or overriding at the client level (less preferred but acceptable)

**Comment by mateusduboli** [comment]
+1

**Comment by farmdawgnation** [comment]
This has been resolved in Dispatch 0.12.x and Dispatch 0.13.x and releases to Maven Central are forthcoming.
