### ISSUE TITLE
oauth signing regression between 0.10.0 and 0.11.0 release versions

### ISSUE THREAD

**Issue by softprops** [dispatch/reboot#75]
a more detailed bug description will be forth coming but I'm jotting this here for reference. It looks like it may have to do with some expectation of parameter encoding.
I was using 0.11.0 and the callback sent to the server didn't seem to be encoded correctly but when I switched back to 0.10.0 things seemed to work fine. Also, not didn't verify this but noticed when the dispatch.oauth.SomeXXX paths ended with a trailing slash the target authorization server ( Meetup ) didn't agree with dispatches generated request signature. Again, will verify some of this stuff later in a more detailed report but I'm jotting these things down before I forget!

**Comment by farmdawgnation** [comment]
@softprops Bump!

**Comment by softprops** [comment]
Sry it's been a long context switch and I havent worked directly with the dispatch + oauth1 signing combo for quite some time. I'd be to fine with closing this out and let a new isdue resurface in its place though more common use if it's still an issue.

**Comment by farmdawgnation** [comment]
Sounds good, thanks!
