### ISSUE TITLE
App never shutdowns when using Dispatch

### ISSUE THREAD

**Issue by simao** [dispatch/reboot#99]
Hello,

I am using some simple code, like suggested in the Dispatch README:

```
    val svc = url(feedUrl)
    Http(svc OK as.String).
```

The problem is my app never terminates, I think some daemon threads are still running in the background.

Is it possible to shutdown the client when using this simple API? Since `HTTP` is just a `Future` I can't even shutdown the client here as  I don't know when it can be executed.

Thanks

**Comment by estaub** [comment]
Invoking Http.shutdown() did it for me.  I'm a newb too, so don't ask me for any details - I just found it in some code somewhere!

**Comment by dk8996** [comment]
We are having the same issue with dispatch not shutting down all the threads.

**Comment by keritaf** [comment]
If you are creating clients with ```Http.configure``` then invoke ```.shutdown()``` on each of them. And if you are using custom ```ExecutionContext``` you may have forgotten to shutdown its ```Executor``` as well.

**Comment by farmdawgnation** [comment]
@simao This issue has grown stale, so I'm guessing it's resolved for you? Please feel free to open a follow-up if you're having other issues.
